config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#index'

  resources :listings

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  resources :users, only: [:show]

  resources :photos, only: [:create, :destroy]do
    collection do
      get :list
    end
  end

  resources :listings do
    resources :reservations, only: [:new, :create]
  end

  get '/setdate' => 'reservations#setdate'
  get '/duplicate' => 'reservations#duplicate'
  get '/reservations' => 'reservations#index'
  get '/reserved' => 'reservations#reserved'

  get 'manage-listing/:id/basics' => 'listings#basics', as: 'manage_listing_basics'
  get 'manage-listing/:id/description' => 'listings#description', as: 'manage_listing_description'
  get 'manage-listing/:id/address' => 'listings#address', as: 'manage_listing_address'
  get 'manage-listing/:id/price' => 'listings#price', as: 'manage_listing_price'
  get 'manage-listing/:id/photos' => 'listings#photos', as: 'manage_listing_photos'
  get 'manage-listing/:id/calender' => 'listings#calender', as: 'manage_listing_calender'
  get 'manage-listing/:id/bankaccount' => 'listings#bankaccount', as: 'manage_listing_bankaccount'
  get 'manage-listing/:id/publish' => 'listings#publish', as: 'manage_listing_publish'

  #stripe connect oauth path
  get '/connect/oauth' => 'stripe#oauth', as: 'stripe_oauth'
  get '/connect/confirm' => 'stripe#confirm', as: 'stripe_confirm'
  get '/connect/deauthorize' => 'stripe#deauthorize', as: 'stripe_deauthorize'
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations
  
  # 必須項目
  validates :home_type, presence: true
  validates :pet_type, presence: true
  validates :pet_size, presence: true
  validates :breeding_years, presence: true

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listing, only: [:show, :update, :basics, :description, :address, :price, :photos, :calender, :bankaccount, :publish]
  before_action :accsess_deny, only: [:basics, :description, :address, :price, :photos, :calender, :bankaccount, :publish]

  def index
    @listings = current_user.listings
  end

  def show
    @photos = @listing.photos
  end

  def new
    @listing = current_user.listings.build
  end

  def create
    @listing = current_user.listings.build(listing_params)
    
    if @listing.save
      redirect_to manage_listing_basics_url(@listing), notice: "リスティングの作成・保存をしました"
    else
      redirect_to new_listing_url, notice: "リスティングの作成・保存出来ませんでした"
    end
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
       redirect_back(fallback_location: root_url)
       flash[:notice] = '更新しました'
    end
  end

  def basics
  end

  def description
  end

  def address
  end

  def price
  end

  def photos
    @photo = Photo.new
  end

  def calender
  end

  def bankaccount
    @user = @listing.user
    session[:listing_id] = @listing.id
  end

  def publish
  end

  private
    def listing_params
      params.require(:listing).permit(:home_type, :pet_type, :breeding_years, :pet_size, :price_pernight, :address, :listing_title, :listing_content, :active)
    end

    def set_listing
      @listing = Listing.find(params[:id])
    end

    def accsess_deny
      if !(current_user == @listing.user)
        redirect_to root_url, notice: "他人の編集ページにはアクセスできません"
      end
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/address.html.erb
<%= render 'partial/navbar' %>
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'partial/verticalnavbar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">住所の編集</span>
                </div>
            </div>

            <div class="panel-body">          

                <%= form_for @listing do |f| %>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>住所</label>
                                <%= f.text_field :address, placeholder: "例: 東京都港区六本木６丁目１１−１", class: "form-control" %>
                            </div>
                        </div>
                    </div>

                    <div class="actions">
                        <%= f.submit "更新", class: "btn btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/listings/bankaccount.html.erb
<%= render 'partial/navbar' %>

<div class="container">
  <div class="col-md-3">
    <!-- vertical-navbar -->
    <%= render 'partial/verticalnavbar'%>
  </div>

  <div class="col-md-9">
      <div class="panel panel-default">
          <div class="panel-heading">
              <div class="text-center">
                  <span style="font-size:24px;">受取口座情報の編集</span>
              </div>
          </div>

          <div class="panel-body">            
              <% if @user.connected? %>
                  <%= render 'stripe/setting' %>
               
              <% else %>

                  <%= render 'stripe/connect' %>
              <% end %>
          </div>
      </div>
  </div>  
</div>

app/views/listings/basics.html.erb
<%= render 'partial/navbar' %>
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'partial/verticalnavbar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
          <div class="panel-heading">
              <div class="text-center">
                  <span style="font-size:24px;">基本データの編集</span>
              </div>
          </div>

          <div class="panel-body">           
              <%= form_for @listing do |f| %>
                  <div class="row">
                      <div class="col-md-12 select">
                          <div class="form-group">
                              <label>お家の種類</label>
                              <%= f.select :home_type, [["一軒家","一軒家"], ["マンション","マンション"], ["アパート","アパート"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                          </div>
                      </div>
                  </div>
                  <br>

                  <div class="row">
                      <div class="col-md-12 select">
                          <div class="form-group">
                              <label>ペットの種類</label>
                              <%= f.select :pet_type, [["犬","犬"], ["猫","猫"], ["鳥類","鳥類"], ["爬虫類","爬虫類"], ["魚類","魚類"], ["両生類","両生類"], ["その他","その他"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                          </div>
                      </div>
                  </div>
                  <br>

                  <div class="row">
                      <div class="col-md-12 select">
                          <div class="form-group">
                              <label>ペットの飼育歴</label>
                              <%= f.select :breeding_years, [["1年",1], ["2年",2], ["3年",3], ["4年",4], ["5年",5], ["6年以上",6]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                          </div>
                      </div>
                  </div>
                  <br>

                  <div class="row">
                      <div class="col-md-12 select">
                          <div class="form-group">
                              <label>ペットのサイズ</label>
                              <%= f.select :pet_size, [["小型","小型"], ["中型","中型"], ["大型","大型"], ["超大型","超大型"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                          </div>
                      </div>
                  </div>
                  <br>

                  <div class="actions">
                      <%= f.submit "更新", class: "btn btn-danger" %>
                  </div>
              <% end %>
          </div>
      </div>
  </div>
</div>

app/views/listings/calender.html.erb
<%= render 'partial/navbar' %>
<div class="container">
  <div class="col-md-3">
    <!-- vertical-navbar -->
      <%= render 'partial/verticalnavbar'%>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="text-center">
          <span style="font-size:24px;">Calendar</span>

        </div>
      </div>

      <div class="panel-body">      

        <!-- datepicker Calendar -->
        <%= form_for([@listing, @listing.reservations.new]) do |f| %>
          <div class="row row-space-top-4">
            <div class="col-md-8 col-md-offset-2 calendar">
              <label>預かりができない日を指定</label>
              <div id="datepicker"></div>
            </div>
          </div>
          <br>
          <hr>

          <!-- 隠し要素として"listing_id"をおくる -->
          <%= f.hidden_field :listing_id, value: @listing.id %>
          <%= f.hidden_field :selectedDates, value: "",id:"selectedDates" %>
          
  
          <div class="actions">
            <%= f.submit "更新", class: "btn btn-danger" %>
          </div>

        <% end %>

      </div>
    </div>
  </div>
</div>

<script>

// http://stackoverflow.com/questions/1452066/jquery-ui-datepicker-multiple-date-selections
// 上のurlを参照

//他人がした予約日
disabledDates = [];

//自分が予約した日付
selectedDates = [];

function addDate(date) {
  if ($.inArray(date, selectedDates) < 0) {
    selectedDates.push(date);
  }
}

function removeDate(index){
  //splice(削除開始位置,削除する要素数)
  selectedDates.splice(index,1);
}

// 選択された日付がすでに"selectedDates"にあれば、削除。なければ追加
function addOrRemoveDate(date) {
    var index = jQuery.inArray(date, selectedDates);
    if (index >= 0) 
      removeDate(index);
    else 
      addDate(date);
}

// カレンダーの選択可能日と不可能日を決める関数
function SelectMultipleDates(date){
  //inArray(value,array) 第一引数に渡した値が配列中にあれば、そのインデックスを返します。
  var gotDateIndex = $.inArray($.datepicker.formatDate($(this).datepicker('option', 'dateFormat'), date), selectedDates);
  var disabledDateIndex = $.inArray($.datepicker.formatDate($(this).datepicker('option', 'dateFormat'), date), disabledDates);

  if (gotDateIndex >= 0) {
    return [true,'class-holiday'];
  }else if(disabledDateIndex >= 0){
    return [false,''];
  }else{
    return [true, ""];
  }
}

// メインの処理　
$(function () {
  $.ajax({
    url: '/setdate',
    // this data is data for sending to url
    data: {'listing_id': <%= @listing.id %>},
    dataType: 'json',
    // callback argument: data is the response data
    success: function(data){
   
      $.each(data,function(arrID,arrValue){
        //自分で予約した日付"selectedDates[]"と他人が予約した日付"disabledDates[]"をわけてpushしなきゃいけない
        for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1 )){

          // 自分で予約した場合の日付
          if(arrValue.user_id == <%= current_user.id %>){
            selectedDates.push($.datepicker.formatDate('d-m-yy',d));
            $('#selectedDates').val(selectedDates);
          }else{
            disabledDates.push($.datepicker.formatDate('d-m-yy',d));
          }            
        }       
      });

      $("#datepicker").datepicker({
          dateFormat: "d-m-yy",
          minDate: 0, // Unix timestamp
          beforeShowDay:SelectMultipleDates,
          onSelect: function(dateText, inst){
              addOrRemoveDate(dateText);
              $('#btn-book').attr('disabled', false);
              $('#selectedDates').val(selectedDates);
              //ruby controller 内で　, で区切って配列化
              console.log("セレクト");
              console.log(selectedDates);
              console.log("ディスエイブル");
              console.log(disabledDates);
          }
      });
    }
  });
});
</script>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/description.html.erb
<%= render 'partial/navbar' %>
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'partial/verticalnavbar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">リスティング内容の編集</span>
                </div>
            </div>

            <div class="panel-body">            

                <%= form_for @listing do |f| %>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>タイトル</label>
                                <%= f.text_field :listing_title, placeholder: "リスティングタイトルを記載しましょう", class: "form-control" %>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>内容</label>
                                <%= f.text_area :listing_content, rows: 8, placeholder: "リスティングの内容について記述してください", class: "form-control" %>
                            </div>                            
                        </div>
                    </div>
            

                    <div class="actions">
                        <%= f.submit "更新", class: "btn btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/listings/edit.html.erb
<h1>Listings#edit</h1>
<p>Find me in app/views/listings/edit.html.erb</p>

app/views/listings/index.html.erb
<%= render 'partial/navbar' %>

<div class="container"> 
    <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:18px;">リスティング一覧</span>
                </div>
            </div>
            <ul class="ul-unstyled">
                <% @listings.each do |listing| %>
                    <li class="panel-body">
                        <div class="row-table">
                            <div class="col-md-3 col-sm-3 col-middle row-space-2">
                                <div class="panel-list-img text-center">
                                    <%= image_tag listing.photos[0].image.url(:medium) if listing.photos.length > 0  %>    
                                </div> 
                            </div>

                            <div class="col-sm-7 col-lg-7 col-middle row-space-2">
                                <span class="listing-title"><%= listing.listing_title %></span>
                            </div>
                            
                            <div class="col-md-3 col-sm-3 col-middle row-space-1">
                                <%= link_to "残り5ステップ", manage_listing_basics_path(listing), class: "btn btn-primary pull-right" %>
                            </div>
                        </div>
                    </li>
                <% end %>               
            </ul>     
        </div>
        
    </div>
</div>

app/views/listings/new.html.erb
<%= render 'partial/navbar' %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="text-center">
            <span style="font-size:24px;">ペットリスティングを掲載する</span>
          </div>
        </div>
      
        <div class="panel-body">      
          <!-- ここからフォーム -->
          <%= form_for @listing do |f| %>
            <div class="row">
              <div class="col-md-12 select">
                <div class="form-group">
                  <label>お家の種類</label>
                  <%= f.select :home_type, [["一軒家","一軒家"], ["マンション","マンション"], ["アパート","アパート"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                </div>
              </div>
            </div>
            <br>

            <div class="row">
              <div class="col-md-12 select">
                <div class="form-group">
                  <label>ペットの種類</label>
                  <%= f.select :pet_type, [["犬","犬"], ["猫","猫"], ["鳥類","鳥類"], ["爬虫類","爬虫類"], ["魚類","魚類"], ["両生類","両生類"], ["その他","その他"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                </div>
              </div>
            </div>
            <br>

            <div class="row">
              <div class="col-md-12 select">
                <div class="form-group">
                  <label>ペットの飼育歴</label>
                  <%= f.select :breeding_years, [["1年",1], ["2年",2], ["3年",3], ["4年",4], ["5年",5], ["6年以上",6]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                </div>
              </div>
            </div>
            <br>

            <div class="row">
              <div class="col-md-12 select">
                <div class="form-group">
                  <label>ペットのサイズ</label>
                  <%= f.select :pet_size, [["小型","小型"], ["中型","中型"], ["大型","大型"], ["超大型","超大型"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                </div>
              </div>
            </div>
            <br>

            <div class="actions">
              <%= f.submit "Save", class: "btn btn-danger" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/listings/photos.html.erb
<%= render 'partial/navbar' %>
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'partial/verticalnavbar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">リスティング写真の編集</span>
                </div>
            </div>

            <div class="panel-body">          
                <%= form_for @photo, html:{ multipart: true, class: "dropzone", id: "my-dropzone" } do |f| %> 
                    
                    <%= f.hidden_field :listing_id, value: @listing.id %>
                    <div class="dz-message needsclick">
                        <h3>ファイルをここにドロップしてください。</h3>
                        <strong>アップロードするにはここをクリックしてください</strong>
                    </div>
                    
                    <div class="fallback">
                        <%= f.file_field :image %>
                        <%= f.submit "Upload image" %>
                    </div>

                <% end %>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
  $(function () {
  Dropzone.autoDiscover = false;
  //photos_controller.rbのcreateアクションが呼ばれる
  $("#my-dropzone").dropzone({
    maxFilesize: 200,// MB
    addRemoveLinks: true,//削除リンク,Cancelリンクを全てのpreviewファイルに付ける。 
    paramName: 'photo[image]',// パラメータの名前
    success: function(file, response) {
      // file.previewElementでpreview要素のhtmlにアクセスできる
      //add .dz-success class to file.previewElement 
      $(file.previewElement).addClass('dz-success');
      //add response.uploadId to .dz-remove class
      $(file.previewElement).find('.dz-remove').attr('id', response.photoId);
    },
    removedfile: function(file) {
      // 削除選択されたfileのidを取得
      var id = $(file.previewTemplate).find('.dz-remove').attr('id');
      //call photos_controler.rb destroy action
      $.ajax({
        type: 'DELETE',
        url: "/photos/" + id,
        success: function(data) {
          console.log(data.message);
        }
      });

      var previewElement;
      // 条件式 ? 式1 : 式2　条件式の値がtrue=>式1、false=>式2返します。
      //parentNode => 親ノード（一つ上のhtml要素)を取得.
      //(void 0) => 何も処理しない
      // リスト（親ノード）から、プレビュー要素を消すという記述
      return (previewElement = file.previewElement) != null ? (previewElement.parentNode.removeChild(file.previewElement)) : (void 0);
    },
    // init executed at first when Page loaded
    init: function() {
      //this equal dropzone
      var me = this;

      //meに"complete"イベントを定義
      me.on("complete", function(file) {
       $(file.previewTemplate).find('.dz-remove').text("削除する");
      }); 
      //call list function in photos_controller.rb with get method
      $.ajax({
       type: "GET",
       url: "/photos/list",
       data: {'listing_id': <%= @listing.id %>},
           dataType: 'json',
       success: function(data){
           $.each(data.images, function(key, value) {
             if (data.images != undefined && data.images.length > 0) {
               me.emit("addedfile", value); //addedfileイベントをvalueのデータで実行する
               me.emit("thumbnail", value, value.src);//thumbnailイベントをvalueのデータで実行する
               me.emit("complete", value);  //completeイベントをvalueのデータで実行する
               $(value._removeLink).attr("id", value.id); //valueの_removeLinkのidにvalue.idを追加
             }
           });
       }
      });
    }
  });
});
</script>

app/views/listings/price.html.erb
<%= render 'partial/navbar' %>
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'partial/verticalnavbar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">料金の設定</span>
                </div>
            </div>

            <div class="panel-body">            

                <%= form_for @listing do |f| %>

                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                          <label>一泊あたりの料金</label>
                          <div class="input-group">
                            <div class="input-group-addon">円</div>
                            <%= f.text_field :price_pernight, placeholder: "例: 100", class: "form-control" %>
                          </div>  
                        </div>
                      </div>
                    </div>    

                    <div class="actions">
                        <%= f.submit "更新", class: "btn btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/listings/publish.html.erb
<%= render 'partial/navbar' %>
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'partial/verticalnavbar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">公開する</span>
                </div>
            </div>

            <div class="panel-body">            

                <%= form_for @listing do |f| %>

                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                            <%= f.select :active, [["公開する","true"], ["非公開にする","false"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                        </div>
                      </div>
                    </div>
        
                    <div class="actions">
                        <%= f.submit "更新", class: "btn btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>